SET SQL_SAFE_UPDATES = 0;

CREATE DATABASE IF NOT EXISTS petCare;

USE petCare;

CREATE TABLE IF NOT EXISTS GRUPO_USUARIO(
    ID_ACESSO CHAR(36) PRIMARY KEY NOT NULL,
    ROLE_MYSQL VARCHAR(50),
    TIPO_ACESSO VARCHAR(20),
    DESCRICAO VARCHAR(225)
);

CREATE TABLE IF NOT EXISTS USUARIO(
    ID_USUARIO CHAR(36) PRIMARY KEY NOT NULL,
    NOME_COMPLETO VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(225) NOT NULL,
    SENHA VARCHAR(64) NOT NULL,
    GRUPO_USUARIO CHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTE(
    ID_USUARIO CHAR(36) PRIMARY KEY NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    BAIRRO VARCHAR(30),
    RUA INT(3),
    CIDADE VARCHAR(50),
    CPF BIGINT(11) UNIQUE NOT NULL,
    ID_PET INT NOT NULL
);

CREATE TABLE IF NOT EXISTS PET(
    ID_PET INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    NOME VARCHAR(100),
    RACA VARCHAR(100),
    IDADE FLOAT,
    OBSERVACOES TEXT(250),
    ID_VACINAS INT
);

CREATE TABLE IF NOT EXISTS VACINAS(
    ID_VAC INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50),
    DOSE INT,
    DATA_APLICADO DATE
);

CREATE TABLE IF NOT EXISTS VETERINARIO(
    CRMV INT NOT NULL PRIMARY KEY,
    ID_USUARIO CHAR(36) NOT NULL,
    SALARIO DOUBLE(7,2),
    TURNO VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS CONSULTA(
    ID_PROCEDIMENTO CHAR(36) PRIMARY KEY NOT NULL,
    DATA_CONSULTA DATE,
    VALOR DOUBLE(7,2),
    ID_PET INT NOT NULL,
    CRMV INT NOT NULL
);

/* CONSTRAINTS */

ALTER TABLE USUARIO
ADD CONSTRAINT FK_GRUPO_USUARIO
FOREIGN KEY (GRUPO_USUARIO) REFERENCES GRUPO_USUARIO(ID_ACESSO);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_ID_PET
FOREIGN KEY (ID_PET) REFERENCES PET(ID_PET);

ALTER TABLE PET
ADD CONSTRAINT FK_ID_VACINAS
FOREIGN KEY (ID_VACINAS) REFERENCES VACINAS(ID_VAC);

ALTER TABLE CONSULTA
ADD CONSTRAINT FK_CONSULTA_PET
FOREIGN KEY (ID_PET) REFERENCES PET(ID_PET);

ALTER TABLE CONSULTA
ADD CONSTRAINT FK_CRMV
FOREIGN KEY (CRMV) REFERENCES VETERINARIO(CRMV);

-- VIEW QUE SERÁ UTILIZADA NA PÁGINA DO CLIENTE, MOSTRANDO AS INFORMAÇÕES DO SEU PET --

CREATE OR REPLACE VIEW INFO_PET AS
SELECT P.NOME, U.NOME_COMPLETO, RACA, OBSERVACOES
FROM PET P
INNER JOIN USUARIO U
INNER JOIN CLIENTE C
WHERE U.ID_USUARIO = C.ID_USUARIO AND P.ID_PET = C.ID_PET;

-- VIEW QUE SERÁ UTILIZADA PARA VERIFICAR O HISTÓRICO DE VACINA DO PET --

CREATE OR REPLACE VIEW HISTORICO_VACINA AS
SELECT V.NOME, V.DOSE, V.DATA_APLICADO
FROM VACINAS V
INNER JOIN PET P
WHERE V.ID_VAC = P.ID_VACINAS;
    
/* FUNCTION */

-- FUNÇÃO QUE VAI GERAR UM UUID ALEATÓRIO PARA CADA DADOS CRÍTICOS INSERIDOS NO BANCO. AUXILIA NA SEGURANÇA CONTRA INVASORES --

DELIMITER //
CREATE FUNCTION IF NOT EXISTS gera_id_dados_criticos()
RETURNS CHAR(36)
DETERMINISTIC
BEGIN
    RETURN UUID();
END //
DELIMITER ;

/* PROCEDURE */

-- PROCEDURE QUE IRÁ LISTAR AS CONSULTAS DO DIA PARA O VETERINÁRIO --

DELIMITER //
CREATE PROCEDURE IF NOT EXISTS listar_consultas (IN DATA_CONSULTA_PARAM DATE)
BEGIN
    SELECT C.DATA_CONSULTA, P.NOME, P.RACA
    FROM CONSULTA C
    INNER JOIN PET P
    ON C.ID_PET = P.ID_PET
    WHERE C.DATA_CONSULTA = DATA_CONSULTA_PARAM;
END//
DELIMITER ;

/* TRIGGERS */

-- TRIGGER QUE TRANSFORMA A SENHA INFORMADA EM HASH PARA AUMENTAR A SEGURANÇA --

DELIMITER //
CREATE TRIGGER IF NOT EXISTS hash_senha
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN 
    IF CHAR_LENGTH(NEW.SENHA) < 60 THEN
        SET NEW.SENHA = SHA2(NEW.SENHA, 256);
    END IF;
END //
DELIMITER ;

-- TRIGGER QUE ATUALIZA A NOVA SENHA EM HASH --

DELIMITER //
CREATE TRIGGER IF NOT EXISTS hash_atualiza
BEFORE UPDATE ON USUARIO
FOR EACH ROW
BEGIN
    IF NEW.SENHA <> OLD.SENHA THEN
        SET NEW.SENHA = SHA2(NEW.SENHA, 256);
    END IF;
END //
DELIMITER ;

/* INDEXES */

-- INDEX PARA AUXILIAR A PROCEDURE NAS CONSULTAS DO DIA --

CREATE INDEX IF NOT EXISTS IDX_DATA_CONSULTA ON CONSULTA(DATA_CONSULTA);

-- INDEX PARA AUXILIAR NA BUSCA APÓS LOGIN --

CREATE INDEX IF NOT EXISTS IDX_USUARIO_EMAIL ON USUARIO(EMAIL);

/* ROLES */

-- PARA CONTROLE DE ACESSO --

DROP ROLE IF EXISTS 'ADM', 'VET', 'CLI';

CREATE ROLE 'ADM', 'VET', 'CLI';

-- PERMISSÃO TOTAL PARA ADMINISTRADORES --

GRANT ALL PRIVILEGES ON petCare.* TO 'ADM';

-- PERMISSÃO ESPECÍFICA PARA VETERINÁRIOS --

GRANT SELECT, INSERT, UPDATE ON petCare.PET TO 'VET';
GRANT SELECT, INSERT, UPDATE ON petCare.CONSULTA TO 'VET';
GRANT SELECT, INSERT, UPDATE ON petCare.VACINAS TO 'VET';
GRANT SELECT, INSERT, UPDATE ON petCare.CLIENTE TO 'VET';

GRANT SELECT ON petCare.USUARIO TO 'VET';
GRANT SELECT ON petCare.VETERINARIO TO 'VET';

GRANT EXECUTE ON PROCEDURE petCare.listar_consultas TO 'VET';

-- PERMISSÃO RESTRITA PARA CLIENTES --

GRANT SELECT ON petCare.INFO_PET TO 'CLI';
GRANT SELECT ON petCare.VACINAS TO 'CLI';
